import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'
import logo from './assets/logo.png'
import { motion } from 'framer-motion'
import { useState } from 'react'
import About from '../components/About'
import Link from 'next/link'

export default function Home() {

  const [about, setAbout] = useState(false)

  const handlepop = (data) => { 
    setAbout(data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="head">
        <Image src={logo} alt="logo" width={'120px'} height={'120px'}/>
      </div>
      <div className="outercontainer">
        <div className="buttoncontainer">
          <Link href="/recommendation"><motion.div
            whileHover={{
              scale: 1.1,
              cursor: 'pointer'
            }}
            whileTap={{
              scale: 0.9
            }}
          >
            <Button/>
          </motion.div></Link>
        </div>
      </div>
      <footer className="footer">
        <p onClick={()=>handlepop(true)}>About</p>
      </footer>
      {about && <About handlepop={handlepop}/>}
      <style jsx>{`
        .outercontainer{
          width: 100%;
          height: 60%;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .footer{
          width: 100%;
          height: 20%;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .head{
          width: 100%;
          height: 20%;
          display: flex;
          justify-content: center;
          align-items: center;
        }

        .footer p{
          color: #0085FF;
          font-size: 0.6rem;
          text-decoration: underline;
        }

        .footer p:hover{
          cursor: pointer;
        }
      `}</style>
    </div>
  )
}
